In [2]:
import numpy as np

In [3]:
# What is the shape of the array below?
arr = np.array([1, 2, 3])
print("1. arr shape ", arr.shape)
# Strides mean the number of bytes to skip along each axis to 
# access the next element
print("1. arr.strides: ", arr.strides)

1. arr shape  (3,)
1. arr.strides:  (4,)


In [4]:
# What is the shape of the array below?
arr = np.array([[1, 2, 3]])
print("2. arr shape ", arr.shape)

2. arr shape  (1, 3)


In [5]:
# What is the shape of the array below?
arr = np.array([[[1, 2, 3]]])
print("3. arr shape ", arr.shape)


3. arr shape  (1, 1, 3)


In [6]:
# This is to understand broadcasting feature of NumPy
A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])
print(A * B)

[ 4. 10. 18.]


In [7]:
# Create a 3x3 matrix
A3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A3x3 ndim ", A3x3.ndim)
print("A3x3 shape ", A3x3.shape)
print("A3x3.strides: ", A3x3.strides)


A3x3 ndim  2
A3x3 shape  (3, 3)
A3x3.strides:  (12, 4)


In [8]:
# With broadcasting, no restriction that both vectors have to be of
# the same size. The missing entries are filled with the given value.
A = np.array([1.0, 2.0, 3.0])
B = np.array([2.0])
C = A * B
print("A shape ", A.shape)
print("B shape ", B.shape)
print("C shape ", C.shape)
print(C)


A shape  (3,)
B shape  (1,)
C shape  (3,)
[2. 4. 6.]


In [9]:
# Create a 1D array (vector)
A = np.array([1.0, 2.0, 3.0])
B = np.array([[2, 2, 2], [3, 3, 3]])
print("A shape ", A.shape)
print("B shape ", B.shape)

A shape  (3,)
B shape  (2, 3)


In [10]:
# Broadcasting allows adding a 1D array to a 2D array
C = A + B
print("C shape ", C.shape)
print("C strides ", C.strides)
print(C)

C shape  (2, 3)
C strides  (24, 8)
[[3. 4. 5.]
 [4. 5. 6.]]


In [11]:
# Try to find the shape of these arrays and the strides of each and 
# the result array
K = np.array([[1, 1], [2, 2]])
L = np.array([3, 3])
M = np.array([[4, 4], [5, 5], [6, 6]])
print("K shape ", K.shape)
print("L shape ", L.shape)
print("M shape ", M.shape)
print("K strides ", K.strides)
print("L strides ", L.strides)
print("M strides ", M.strides)

K shape  (2, 2)
L shape  (2,)
M shape  (3, 2)
K strides  (8, 4)
L strides  (4,)
M strides  (8, 4)


In [12]:
# Can this operation be done? Will broadcasting work here?
#result = K + L + M

# How to make it work with one change either to K or M in its shape?
# Either make the shape K as (3, 2) or M as (2, 2)
# Let us try one at a time
# Change shape of K as (3, 2)
K = np.array([[1, 1], [2, 2], [3, 3]])
L = np.array([3, 3])
M = np.array([[4, 4], [5, 5], [6, 6]])
result = K + L + M
print("result shape ", result.shape)
print(result)

result shape  (3, 2)
[[ 8  8]
 [10 10]
 [12 12]]


In [13]:
# From here, in the file Ses3D_Broadcast_2
# Broadcasting: Scaling an RGB array with a 1D array
colourPlanes = (8, 8, 3)
npImage = np.ones(colourPlanes)
print('\nInitalized Image:')
print('   R  G  B planes each of 8x8 npImage')
print(npImage)


Initalized Image:
   R  G  B planes each of 8x8 npImage
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
# The last entry (3) refers to three colour planes RGB
# How can we access the Red plane which is 8x8?
# We can use slicing. Just mentioning : means all the elements of that axis
redPlane = npImage[:, :, 0] # Red plane
print('\nRed plane')
print(redPlane)


Red plane
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
# Note that redPlane is a new object view of the same original npImage
# Any changes to the redPlane affects the original npImage
colourScale = np.array([2, 3, 4])
print('Colour scaling 1D array')
print(' R G B scaling factor 1x3 size')
print(colourScale)
scaledImage = npImage * colourScale
print('\nScaled Image:')
print('   R  G  B planes each of 8x8 size')
print(scaledImage)


Colour scaling 1D array
 R G B scaling factor 1x3 size
[2 3 4]

Scaled Image:
   R  G  B planes each of 8x8 size
[[[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]]


In [16]:
# does scaledImage and npImage refer to the same memory?
print("id of npImage ", id(npImage))
print("id of scaledImage ", id(scaledImage))
# Note that element-wise operations in NumPy create new arrays, 
# rather than modifying the original array in place



id of npImage  2267390481808
id of scaledImage  2267390482576


In [17]:
# Let us use slicing to see different planes of the scaled image
redPlane = scaledImage[:, :, 0] # Red plane of scaled image
print('\nRed plane of scaled image')
print(redPlane)


Red plane of scaled image
[[2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2.]]


In [18]:
# Note that slicing does not create a new copy, the redPlane is a 
# new view of the original scaledImage, though new object is created
# to refer to a new view of the original object
print("id of the scaledImage ", id(scaledImage))
print('id of redPlane before scaling', id(redPlane))


id of the scaledImage  2267390482576
id of redPlane before scaling 2267390486032


In [19]:
greenPlane = scaledImage[:, :, 1] # Green plane of scaled image
print('\nGreen plane of scaled image')
print(greenPlane)



Green plane of scaled image
[[3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]]


In [20]:

bluePlane = scaledImage[:, :, 2] # Blue plane of scaled image
print('\nBlue plane of scaled image')
print(bluePlane)


Blue plane of scaled image
[[4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4.]]


In [21]:
# Let us see the shape of these colour planes
print('Shaeps of RGB planes are: ', redPlane.shape, 
      greenPlane.shape, bluePlane.shape)

Shaeps of RGB planes are:  (8, 8) (8, 8) (8, 8)


In [22]:
# Let us scale up differnt colour components by different values
redScale = 10
greenScale = 20
blueScale = 30

# Scale down by dividing the Red plane with redScale
# Here, a new redPlane is created for the element-wise operation
redPlane = redPlane / redScale
print('id of redPlane after scaling', id(redPlane))

print('\nScaled down Red plane')
print(redPlane)

print('\n scaledImage is not affected now ...')
print(scaledImage)

id of redPlane after scaling 2267390486704

Scaled down Red plane
[[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]]

 scaledImage is not affected now ...
[[[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]]

 [[2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3. 4.]
  [2. 3

In [23]:
redPlane = scaledImage[:, :, 0] # Red plane of scaled image
# The operator /= is in-place operator for mutable objects in Python
# It does not create a new object, the orginal scaledImage is modified.
redPlane /= redScale
print('\nScaled down Red plane now')
print(redPlane)

print('\n scaledImage is affected now with /= in-place operator ...')
print(scaledImage)

print('id of scaledImage before scaling', id(scaledImage))
# To apply the scaling on the original image itself
# Another method of performing an in-place operation is given below
scaledImage[:, :, 0] = scaledImage[:, :, 0] / redScale
print('id of scaledImage after scaling', id(scaledImage))

print('\n Affected scaled image after the scaling done on it...')
print(scaledImage)



Scaled down Red plane now
[[0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]]

 scaledImage is affected now with /= in-place operator ...
[[[0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]]

 [[0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]]

 [[0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]]

 [[0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]]

 [[0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]
  [0.2 3.  4. ]


In [24]:
# Some more Broadcasting examples
npA3 = np.arange(2, 5)
print("npA3: ", npA3)

npB5_4_3 = np.ones((5, 4, 3))
print("npB5_4_3:\n", npB5_4_3)

npNew5_4_3 = npB5_4_3 + npA3
print("npNew5_4_3:\n", npNew5_4_3)

npA2 = np.arange(2, 4)
print("npA2:", npA2)


npA3:  [2 3 4]
npB5_4_3:
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
npNew5_4_3:
 [[[3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]]

 [[3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]]

 [[3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]]

 [[3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]]

 [[3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]]]
npA2: [2 3]


In [25]:
# Is it possible to do this operation? 
# Uncomment and check it out.
#npNew = npNew5_4_3 + npA2

# Define A (4D array)
A = np.ones((8, 1, 6, 1))

# Define B (3D array)
B = np.ones((7, 1, 5))

# Perform broadcasting (e.g., addition)
result = A + B

print("Shape of A:", A.shape)


print("Shape of B:", B.shape)


print("Shape of result:", result.shape)
print("result:\n", result)





Shape of A: (8, 1, 6, 1)
Shape of B: (7, 1, 5)
Shape of result: (8, 7, 6, 5)
result:
 [[[[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]]

  [[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]]

  [[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]]

  ...

  [[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]]

  [[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]]

  [[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]]]


 [[[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]]

  [[2. 2. 2. 2. 2.]
   [2. 2. 2. 2. 2.]
   [2. 2. 2

In [26]:





# Sample code explaining the slice and the original arrays
# referring to the same data in the memory

# Create a 2D NumPy array
original_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice the array (create a view)
sliced_arr = original_arr[:, 1]

# Check the id of the original and sliced array
print("ID of original array:", id(original_arr))  # Different object
print("ID of sliced array:", id(sliced_arr))      # Different object

print("Original array contents:", original_arr)

print("Sliced array contents:", sliced_arr)


# Modify the sliced array
sliced_arr[0] = 100

# Check if the change is reflected in the original array
print("Original array after modifying the slice:")
print(original_arr)


ID of original array: 2267390486704
ID of sliced array: 2267390487856
Original array contents: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced array contents: [2 5 8]
Original array after modifying the slice:
[[  1 100   3]
 [  4   5   6]
 [  7   8   9]]
