In [4]:
import numpy as np
import sys
import platform

<h3>Numpy dtypes</h3>

In [5]:
print('Python interpreter version running on Windows PE')
print(type(platform.architecture())) 
print(type(platform.architecture()[0]))
print(len(platform.architecture()))
print(platform.architecture())
print(platform.architecture()[0])
print(platform.architecture()[1])

class X:
    def __init__(self, name):
        self.name = name
    
    def __str__(self):
      return 'I am am instance of class X\n'  + 'My name is ' + self.name

class Y:
    def __init__(self, name):
        self.name = name
    
    def __str__(self):
      return 'I am am instance of class Y\n'  + 'My name is ' + self.name

class Z:
    def __init__(self, name):
        self.name = name
    
    def __str__(self):
      return 'I am am instance of class Z\n'  + 'My name is ' + self.name

objX = X('ObjX')
objY = Y('ObjY')
objZ = Z('ObjZ')

npObjX = np.object_(objX)
print('\nAbout dtype object')
print('Type: ', type(npObjX))
print('Value: ', npObjX)


npObjArr = np.ndarray(3, dtype=object)

npObjArr[0] = objX
npObjArr[1] = objY
npObjArr[2] = objZ

print('\nAbout NumPy array of objects')
print('Item size of objXArr is ', npObjArr.itemsize)
print('Number of elements in the npObjXArr is ', npObjArr.size)
print('Total size in bytes, taken by npObjXArr is ', 
      npObjArr.size * npObjArr.itemsize)

for i in range(3):
    print('\nDetails of npObjArr[', i, ']', sep='')
    print('Type: ', type(npObjArr[i]))
    print('Value: ', npObjArr[i])

# About Overflows in NumPy which does not happen with Python ints
npPow64 = np.power(100, 8, dtype=np.int64)
print('\nAbout overflows in NumPy')
print('Value of 100^8 using int64', npPow64)
npPow32 = np.power(100, 8, dtype=np.int32)
print('Value of 100^8 using int32', npPow32)

# Incorrect even with 64-bit int, then float64 can be used instead
npPow64 = np.power(100, 100, dtype=np.int64) 
print('Value of 100^100 using npPow64', npPow64)
npPowF64 = np.power(100, 100, dtype=np.float64) 
print('Value of 100^100 using npPowF64', npPowF64)

# About byteorder
dt = np.dtype('i2') # An  integer with two bytes
print('Byte order of two bytes int is: ', dt.byteorder) # Native endianess
print('Item size is ', dt.itemsize)

# Learn about endiness of the machine this is running on
print('Endianess: ', np.dtype(np.uintc).byteorder)
print('Endianess: ', np.dtype(np.ubyte).byteorder)

print('System byteorder: ', sys.byteorder)

intNonNative = np.dtype(np.uintc).newbyteorder('S')
print(type(intNonNative))
print('Non-native byteorder is ', intNonNative.byteorder)
intNative = np.dtype(np.uintc).newbyteorder('S').newbyteorder('S')
print('Native byteorder is ', intNative.byteorder)


Python interpreter version running on Windows PE
<class 'tuple'>
<class 'str'>
2
('64bit', 'WindowsPE')
64bit
WindowsPE

About dtype object
Type:  <class '__main__.X'>
Value:  I am am instance of class X
My name is ObjX

About NumPy array of objects
Item size of objXArr is  8
Number of elements in the npObjXArr is  3
Total size in bytes, taken by npObjXArr is  24

Details of npObjArr[0]
Type:  <class '__main__.X'>
Value:  I am am instance of class X
My name is ObjX

Details of npObjArr[1]
Type:  <class '__main__.Y'>
Value:  I am am instance of class Y
My name is ObjY

Details of npObjArr[2]
Type:  <class '__main__.Z'>
Value:  I am am instance of class Z
My name is ObjZ

About overflows in NumPy
Value of 100^8 using int64 10000000000000000
Value of 100^8 using int32 1874919424
Value of 100^100 using npPow64 0
Value of 100^100 using npPowF64 1e+200
Byte order of two bytes int is:  =
Item size is  2
Endianess:  =
Endianess:  |
System byteorder:  little
<class 'numpy.dtypes.UIntDType'>
Non

<h3>Numpy Endianess</h3>

In [6]:
arr = np.array([0, 1, 2, 3])
print(arr)
print("id(arr) = ", id(arr))

# Individual elements of a NumPy array can be modified without changing its size
arr[0] = 10
print(arr)
print("id(arr) = ", id(arr))

# Adding a new element or changing the size of NumPy array creates a new array
arr = np.append(arr, 4)
print(arr)
print("id(arr) = ", id(arr))

# Let us understand the contents of different integer values in NumPy
npMyInt32 = np.int32(5)
print("value in npMyInt32 is ", npMyInt32)
print("Size of npMyInt32 is ", npMyInt32.nbytes)
print("Binary contents of npMyInt32 is ", npMyInt32.tobytes())

npMyInt64 = np.int64(-2)
print("value in npMyInt64 is ", npMyInt64)
print("Size of npMyInt64 is ", npMyInt64.nbytes)
print("Binary contents of npMyInt64 is ", npMyInt64.tobytes())

print("Can you understand the byte contents?")
print("What is the endinaness of the machine this is running on?")

# Get the byte order (endianess of the machine)
# Ref: https://numpy.org/doc/stable/reference/generated/numpy.dtype.byteorder.html

# Get the endianess of the system
print(sys.byteorder)

# Different values of the byteorder attribute of NumPy
# byteorder is an attribute of NumPy arrays (ndarray) and data types (dtype)
# ‘=’ : native
# ‘<’ : little-endian
# ‘>’ : big-endian
# ‘|’   : not applicable

# Is endianess relevant for a byte value?
print("Endianess of a byte: ", np.dtype('i1').byteorder)

# Is endianess relevant for a byte value?
print("Endianess of a short or int16: ", np.dtype('i2').byteorder)

npMyInt32 = np.int32(8)

print("Value in npMyInt32 is ", npMyInt32)
print("Value in npMyInt32 in hex is ", hex(npMyInt32))

print("Endianess or byteorder of npMyInt32 is ", npMyInt32.dtype.byteorder)
print("Print the byte contents of npMyInt32: ", npMyInt32.tobytes())

# Change the byteorder of the NumPy variable (in-place is not allowed)
npMyInt32New = npMyInt32.byteswap()
print("Value in npMyInt32New is ", npMyInt32New)
print("Value in npMyInt32New in hex is ", hex(npMyInt32New))

print("Swapped byte contents of npMyInt32New: ", npMyInt32New.tobytes())

# Byteswap in-place is not allowed on a scalar value in NumPy
#npMyInt32.byteswap(inplace=True)

[0 1 2 3]
id(arr) =  1944777379536
[10  1  2  3]
id(arr) =  1944777379536
[10  1  2  3  4]
id(arr) =  1944780745168
value in npMyInt32 is  5
Size of npMyInt32 is  4
Binary contents of npMyInt32 is  b'\x05\x00\x00\x00'
value in npMyInt64 is  -2
Size of npMyInt64 is  8
Binary contents of npMyInt64 is  b'\xfe\xff\xff\xff\xff\xff\xff\xff'
Can you understand the byte contents?
What is the endinaness of the machine this is running on?
little
Endianess of a byte:  |
Endianess of a short or int16:  =
Value in npMyInt32 is  8
Value in npMyInt32 in hex is  0x8
Endianess or byteorder of npMyInt32 is  =
Print the byte contents of npMyInt32:  b'\x08\x00\x00\x00'
Value in npMyInt32New is  134217728
Value in npMyInt32New in hex is  0x8000000
Swapped byte contents of npMyInt32New:  b'\x00\x00\x00\x08'


<h3>Numpy ndarrays</h3>

In [7]:
a = np.array([0, 1, 2, 3])
print(a)

b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
print(b)

print(b.shape)
print(b.ndim)
print(b[0])
print(b[1])


a = np.arange(10) # 0 .. n-1  (!)
print(a)

aFloat = np.array([1, 2, 3], dtype=float)
print(aFloat)

aComplex = np.array([1+2j, 3+4j, 5+6*1j])
print(aComplex)
print(aComplex.dtype)


[0 1 2 3]
[[0 1 2]
 [3 4 5]]
(2, 3)
2
[0 1 2]
[3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[1. 2. 3.]
[1.+2.j 3.+4.j 5.+6.j]
complex128


In [13]:

my_arr = np.array([1, 2, 3])
print(my_arr.dtype.byteorder)

=


In [14]:
my_arr2 = np.array(['hello', 'wow', 'yes'])
print(my_arr2.dtype.byteorder)

=
